// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnRvPXwBS23grdxDn8Bo4R8XfJF2A7AI',
    appId: '1:474738307458:web:d2c4a8f0b8433c7b12df9b',
    messagingSenderId: '474738307458',
    projectId: 'trend-tracker-1b185',
    authDomain: 'trend-tracker-1b185.firebaseapp.com',
    storageBucket: 'trend-tracker-1b185.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm0QkeOhLZOARphTZvX4zn7D5t-eh4kEY',
    appId: '1:474738307458:android:b80a111c6b06251412df9b',
    messagingSenderId: '474738307458',
    projectId: 'trend-tracker-1b185',
    storageBucket: 'trend-tracker-1b185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxg2rKisn9NlQK66EK2kGV5tFkqOv7-4',
    appId: '1:474738307458:ios:76c9a50c486b31a012df9b',
    messagingSenderId: '474738307458',
    projectId: 'trend-tracker-1b185',
    storageBucket: 'trend-tracker-1b185.appspot.com',
    iosClientId: '474738307458-7h1784gmfsrqip6onnjrcnfu7aq95vvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendTracker',
  );
}
